/// Terms of Service for Crafta
/// Legal compliance with Minecraft EULA and app store requirements
class TermsOfService {
  static const String terms = '''
# Crafta Terms of Service

## 1. Acceptance of Terms
By downloading, installing, or using Crafta ("the App"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, do not use the App.

## 2. Description of Service
Crafta is an educational creative tool that allows users to generate original creatures and furniture for use in Minecraft Bedrock Edition. The App is not affiliated with Mojang Studios or Microsoft Corporation.

## 3. User Responsibilities
- You are responsible for all content you create using the App
- All generated content must comply with Minecraft Community Standards
- You must not create harmful, offensive, or illegal content
- You must not create content that infringes on third-party intellectual property
- You are responsible for ensuring your content is appropriate for your intended audience

## 4. Content Ownership
- All content generated by the App is original and belongs to you
- No Mojang Studios assets, code, or copyrighted material is included in generated content
- You may use, modify, and share your generated content as you see fit
- The App does not claim ownership of your generated content

## 5. Minecraft Integration
- Generated content is designed for use with Minecraft Bedrock Edition
- You must comply with Minecraft's End-User License Agreement when using generated content
- The App is not responsible for how you use generated content in Minecraft
- You may not sell or distribute generated content in ways that violate Minecraft's EULA

## 6. Prohibited Uses
You may not use the App to:
- Create content that violates Minecraft Community Standards
- Generate harmful, offensive, or illegal content
- Create content that infringes on third-party intellectual property
- Attempt to reverse engineer or modify the App
- Use the App for commercial purposes that violate Minecraft's EULA

## 7. Content Moderation
- The App includes content moderation to ensure compliance with community standards
- Content that violates these Terms will be blocked
- We reserve the right to modify content moderation policies
- Users are responsible for ensuring their content complies with all applicable standards

## 8. Privacy
- We collect minimal data necessary to provide the service
- Generated content is stored locally on your device
- We do not share your personal data with third parties
- See our Privacy Policy for more information

## 9. Intellectual Property
- The App and its original content are owned by Crafta
- You may not copy, modify, or distribute the App without permission
- All trademarks and copyrights belong to their respective owners
- The App is not affiliated with Mojang Studios or Microsoft Corporation

## 10. Disclaimers
- The App is provided "as is" without warranties
- We are not responsible for any damages arising from use of the App
- Generated content is provided for educational and creative purposes only
- We make no guarantees about compatibility with Minecraft versions

## 11. Limitation of Liability
- Our liability is limited to the amount you paid for the App
- We are not liable for any indirect, incidental, or consequential damages
- We are not responsible for how you use generated content
- You use the App at your own risk

## 12. Termination
- We may terminate your access to the App at any time
- You may stop using the App at any time
- These Terms remain in effect even after termination
- We may modify or discontinue the App at any time

## 13. Changes to Terms
- We may modify these Terms at any time
- Changes will be effective when posted
- Continued use of the App constitutes acceptance of modified Terms
- We will notify users of significant changes

## 14. Governing Law
- These Terms are governed by applicable law
- Any disputes will be resolved through appropriate legal channels
- These Terms constitute the entire agreement between you and Crafta
- If any provision is invalid, the remaining provisions remain in effect

## 15. Contact Information
For questions about these Terms, contact us at:
- Email: legal@crafta.app
- Website: https://crafta.app/legal

## 16. Minecraft EULA Compliance
- This App complies with Minecraft's End-User License Agreement
- Generated content is original and does not include Mojang assets
- Users must comply with Minecraft Community Standards
- The App is not affiliated with Mojang Studios or Microsoft Corporation

## 17. Educational Purpose
- The App is designed for educational and creative purposes
- It is not intended for commercial use that violates Minecraft's EULA
- Users should use the App responsibly and ethically
- The App promotes creativity and learning in a safe environment

## 18. Age Requirements
- The App is designed for users of all ages
- Parents and guardians are responsible for supervising children's use
- All content must be appropriate for the intended audience
- The App includes content moderation for safety

## 19. Updates and Maintenance
- We may update the App to improve functionality and security
- Updates may include changes to content moderation policies
- We will notify users of significant updates
- Continued use of the App constitutes acceptance of updates

## 20. Third-Party Services
- The App may integrate with third-party services
- We are not responsible for third-party service availability
- Third-party services have their own terms and conditions
- Users are responsible for complying with third-party terms

Last Updated: October 16, 2024
Version: 1.0
''';

  static const String privacyPolicy = '''
# Crafta Privacy Policy

## 1. Information We Collect
- App usage data for improving the service
- Generated content stored locally on your device
- Crash reports and error logs for debugging
- Basic device information for compatibility

## 2. How We Use Information
- To provide and improve the App
- To ensure content compliance with community standards
- To debug and fix technical issues
- To enhance user experience

## 3. Information Sharing
- We do not share personal data with third parties
- Generated content remains on your device
- We may share anonymized usage statistics
- We comply with applicable privacy laws

## 4. Data Security
- We implement appropriate security measures
- Generated content is stored locally
- We do not collect sensitive personal information
- We protect data from unauthorized access

## 5. Children's Privacy
- The App is designed for users of all ages
- We do not knowingly collect personal information from children
- Parents should supervise children's use of the App
- We comply with applicable children's privacy laws

## 6. Your Rights
- You can request information about your data
- You can request deletion of your data
- You can opt out of data collection
- You can contact us with privacy concerns

## 7. Contact Us
For privacy questions, contact us at:
- Email: privacy@crafta.app
- Website: https://crafta.app/privacy

Last Updated: October 16, 2024
Version: 1.0
''';

  static const String contentGuidelines = '''
# Crafta Content Guidelines

## 1. Appropriate Content
- Create family-friendly content
- Ensure content is suitable for all ages
- Use respectful language and imagery
- Promote positive values and creativity

## 2. Prohibited Content
- No harmful or offensive content
- No copyrighted material
- No illegal or dangerous content
- No content that violates community standards

## 3. Minecraft Compliance
- All content must comply with Minecraft Community Standards
- Do not create content that violates Minecraft's EULA
- Respect other players and the community
- Use content responsibly in Minecraft

## 4. Creative Guidelines
- Be original and creative
- Respect intellectual property rights
- Create content that adds value to the community
- Share content responsibly

## 5. Safety Guidelines
- Keep personal information private
- Be respectful to other users
- Report inappropriate content
- Use the App responsibly

## 6. Educational Purpose
- Use the App for learning and creativity
- Share knowledge and ideas
- Help others learn and grow
- Contribute positively to the community

Last Updated: October 16, 2024
Version: 1.0
''';

  /// Get terms of service
  static String getTermsOfService() => terms;

  /// Get privacy policy
  static String getPrivacyPolicy() => privacyPolicy;

  /// Get content guidelines
  static String getContentGuidelines() => contentGuidelines;

  /// Check if user has accepted terms
  static bool hasAcceptedTerms() {
    // Implementation would check local storage
    return true; // Placeholder
  }

  /// Accept terms of service
  static Future<void> acceptTerms() async {
    // Implementation would save to local storage
    // Placeholder implementation
  }

  /// Get version of terms
  static String getTermsVersion() => '1.0';

  /// Check if terms have been updated
  static bool haveTermsBeenUpdated() {
    // Implementation would check if terms have been updated
    return false; // Placeholder
  }
}


